FROM node:16-alpine3.11
# ENV NODE_ENV=production
WORKDIR /app
COPY ["package.json", "package-lock.json*", "npm-shrinkwrap.json*", "./"]
# RUN npm install --production --silent && mv node_modules ../
RUN npm i -g @nestjs/cli
RUN npm install
COPY . .
CMD ["npm", "run", "start:debug"]
