version: '3.4'

services:
  nest-api:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    # depends_on: 
    #   - <name of a service>
